### ISSUE TITLE
Creating WebJob Errors with 400 Bad Request

### ISSUE THREAD

**Issue by evanmoser** [Azure/app-service-linux-docs#234]
When creating a web job in a Linux Web App, an error is returned that simply says Failed with a description of Bad Request. 

Here are the settings I'm establishing for the WebJob, but note that the error returns regardless of the type of file being loaded (.zip or .sh) or the schedule being specified.

![image](https://github.com/Azure/app-service-linux-docs/assets/28511696/38813919-f740-4754-84c6-114779401921)

Here is the message returned.

![image](https://github.com/Azure/app-service-linux-docs/assets/28511696/c2d31151-0837-4d3b-8e9b-be3f4d52463f)

Here is the .sh script I'm attempted to add as a job. The filename is run.sh, but I've tried a variety of file names with no success.

![image](https://github.com/Azure/app-service-linux-docs/assets/28511696/e4420edf-27a9-4d26-b6c7-b4273acab9d4)

In speaking with Azure support, this is a known issue but is not yet publicly documented. They recommended I create an issue here for tracking on a resolution. Any updates you can provide on a resolution would be greatly appreciated. I know WebJobs in Web Apps for Linux are in preview, but unfortunately my code stack doesn't have a Windows Web App option available.

**Comment by evanmoser** [comment]
In continuing to work with Azure support, they recommended adding this to the app configuration:

WEBSITES_ENABLE_APP_SERVICE_STORAGE=true

When this is added, I'm able to create the WebJob without issue.

**Comment by emilepretorius** [comment]
I still cannot add zipped apps to a Linux app service. Is this feature limited to scripts only?

**Comment by evanmoser** [comment]
My understanding is that the app config they suggested would allow either zip or scripts to work. What’s the structure/contents of your zip file?

**Comment by evanmoser** [comment]
> I still cannot add zipped apps to a Linux app service. Is this feature limited to scripts only?

My understanding is that the app config they suggested would allow either zip or scripts to work. What’s the structure/contents of your zip file?

**Comment by emilepretorius** [comment]
> > I still cannot add zipped apps to a Linux app service. Is this feature limited to scripts only?
> 
> My understanding is that the app config they suggested would allow either zip or scripts to work. What’s the structure/contents of your zip file?

The contents of the solution build folder. Same content works for a Windows service. I've tried adding a startup command as some other posts suggest, different regions, nothing works, the upload to the portal simply fails with a generic message (not same as yours, don't recall the exact wording)

![image](https://github.com/user-attachments/assets/1a5cf640-6db3-4ac2-a56f-6310069a94a2)


I've gone back to using a Windows service.

**Comment by porter77** [comment]
I am running into same problem. Have tried a variety of approaches and always get a 400 bad request error when I trying to add a web job to my Linux container service

**Comment by emilepretorius** [comment]
It seems that there needs to be a web app first, then you can add the job ( A friend clevererder than me figured it out ;-) )

**Comment by porter77** [comment]
Not entirely sure what that means - we have a web app that was created via app services. You were able to get this to work with a linux service? I get 400 bad request error no matter what I try, same issue OP is having (it still gives me a bad request error even with WEBSITES_ENABLE_APP_SERVICE_STORAGE=true)

**Comment by emilepretorius** [comment]
Sorry - I should have said: there needs to be something deployed to the web app. It needs to have an entry point.

**Comment by veroca88** [comment]
@evanmoser I'm having the same issue, I’m working on setting up the queue worker for my Laravel app. I’ve set WEBSITES_ENABLE_APP_SERVICE_STORAGE=true and created a storage account in Azure. I also added the following two environment variables:

WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: Linked the app to the storage account.
WEBSITE_CONTENTSHARE: Set the file share name for the Web App.
I’ve verified that the app is running on a PremiumV2 (P1v2) plan, which supports WebJobs.

Do you have any ideas, suggestions, or tips to help make this work? Also, did you keep the same script, or did you modify it?

I appreciate your help with this!

**Comment by evanmoser** [comment]
Hi @veroca88, I'm afraid I ended up having to abandon the WebJob scripting because I kept having issues. My initial configuration changes worked, but eventually my jobs would be deleted with no notice, and I kept having similar issues every time I would try to readd them. If it's helpful, I ended up writing a restricted API endpoint in my Laravel app that runs the queue workers through php artisan and I currently use a Logic App to call that endpoint on a regular schedule. It's not an ideal setup, but it's the only way I could think of to get the workers to run reliably.

**Comment by cedrikbr** [comment]
Just had the same error happen to me while trying to make sure my laravel scheduler kept running, had to abandon WebJobs as well.

**Comment by jackchenwork** [comment]
Looks like this new preview feature is buggy. log stream showed a error when I tried to create a new sample webjob:
2025-02-26T01:35:37.7208941Z Exception StackTrace :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
2025-02-26T01:35:37.7209613Z    at System.Threading.Tasks.Task`1.get_Result()
2025-02-26T01:35:37.7217859Z    at Kudu.Services.Diagnostics.HttpRequestExtensions.ForwardToContainer(String route, HttpRequestMessage request) in /tmp/KuduLite/Kudu.Services/Diagnostics/HttpRequestExtensions.cs:line 51
2025-02-26T01:35:37.7218044Z    at Kudu.Services.Jobs.JobsController.ForwardJobRequestToContainer(String route) in /tmp/KuduLite/Kudu.Services/Jobs/JobsController.cs:line 198
2025-02-26T01:35:37.7266129Z    at Kudu.Services.Jobs.JobsController.ListAllJobs() in /tmp/KuduLite/Kudu.Services/Jobs/JobsController.cs:line 28
2025-02-26T01:35:37.7266500Z    at lambda_method48(Closure , Object , Object[] )
2025-02-26T01:35:37.7270448Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2025-02-26T01:35:37.7270584Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2025-02-26T01:35:37.7270612Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7270635Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2025-02-26T01:35:37.7270654Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7270677Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2025-02-26T01:35:37.7270701Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7270724Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2025-02-26T01:35:37.7270743Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7270771Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2025-02-26T01:35:37.7270828Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2025-02-26T01:35:37.7270852Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7270873Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2025-02-26T01:35:37.7270893Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7270917Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-02-26T01:35:37.7270941Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-02-26T01:35:37.7270961Z    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
2025-02-26T01:35:37.7270985Z    at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 111
2025-02-26T01:35:37.7271010Z Exception StackTrace :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
2025-02-26T01:35:37.7271189Z    at System.Threading.Tasks.Task`1.get_Result()
2025-02-26T01:35:37.7271245Z    at Kudu.Services.Diagnostics.HttpRequestExtensions.ForwardToContainer(String route, HttpRequestMessage request) in /tmp/KuduLite/Kudu.Services/Diagnostics/HttpRequestExtensions.cs:line 512025-02-26T01:35:37.7271424Z    at Kudu.Services.Jobs.JobsController.ForwardJobRequestToContainer(String route) in /tmp/KuduLite/Kudu.Services/Jobs/JobsController.cs:line 198
2025-02-26T01:35:37.7271449Z    at Kudu.Services.Jobs.JobsController.ListAllJobs() in /tmp/KuduLite/Kudu.Services/Jobs/JobsController.cs:line 28
2025-02-26T01:35:37.7271467Z    at lambda_method47(Closure , Object , Object[] )
2025-02-26T01:35:37.7271491Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2025-02-26T01:35:37.7271511Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2025-02-26T01:35:37.7271534Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7271554Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2025-02-26T01:35:37.7271571Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7271592Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2025-02-26T01:35:37.7271639Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7271659Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2025-02-26T01:35:37.7271676Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7285399Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2025-02-26T01:35:37.7285739Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2025-02-26T01:35:37.7285769Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-02-26T01:35:37.7285789Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2025-02-26T01:35:37.7285807Z --- End of stack trace from previous location ---
2025-02-26T01:35:37.7285830Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-02-26T01:35:37.7285851Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-02-26T01:35:37.7285908Z    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
2025-02-26T01:35:37.7285930Z    at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 111
2025-02-26T01:35:37.8359634Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2025-02-26T01:35:37.8360155Z       An unhandled exception has occurred while executing the request.
2025-02-26T01:35:37.8360186Z       System.Net.Http.HttpRequestException: Connection refused (169.254.130.4:50555)
2025-02-26T01:35:37.8373470Z        ---> System.Net.Sockets.SocketException (111): Connection refused
`
It's trying to connect to a http server 169.254.130.4:50555 and failed.

I found 169.254.130.4 is the container's IP address.

On a Linux NodeJS app service container, there is a DiagServer listening on port 50055:

netstat -nap | grep LIST | grep 50
tcp        0      0 0.0.0.0:50055           0.0.0.0:*               LISTEN      1066/./DiagServer  

I suspect the connection is supposed to go to the DiagServer but the port number is wrong.

On a Linux Java app service container, there is no server listening on any 50*** port.







`

**Comment by veroca88** [comment]
If someone still wants to try it, I spoke with azure customer service, and it is require to add some variables in azure env, I've added and now webjob is working 

To resolve this, the following steps were taken:

1. Verify that the environment variables WEBSITE_VNET_ROUTE_ALL = 1 and WEBSITE_CONTENTOVERVNET = 1.
2. Confirm that the script is placed correctly at the root of the queueWorker.zip file with no additional files included.
3. Ensure that the app setting WEBSITE_SKIP_RUNNING_KUDUAGENT is set to false and restart the app.

**Comment by roycedot** [comment]
> If someone still wants to try it, I spoke with azure customer service, and it is require to add some variables in azure env, I've added and now webjob is working
> 
> To resolve this, the following steps were taken:
> 
> 1. Verify that the environment variables WEBSITE_VNET_ROUTE_ALL = 1 and WEBSITE_CONTENTOVERVNET = 1.
> 2. Confirm that the script is placed correctly at the root of the queueWorker.zip file with no additional files included.
> 3. Ensure that the app setting WEBSITE_SKIP_RUNNING_KUDUAGENT is set to false and restart the app.

This worked for me ... sheesh Microsoft documentation is so bad

Thanks for posting!

**Comment by malandles** [comment]
@veroca88 Did it need to be called `queueWorker.zip` and does the script need to be a specific name?

Tried your steps and I keep getting Bad Request. I'm using it for the Laravel schedule run (triggered, to the minute). Might be the difference since you are running the queues on you side.

**Comment by veroca88** [comment]
Hi @malandles, 
You can name the script anything you like. Since my script was small, I didn’t zip it, I uploaded it as `queueworker.sh` but I think it'll be fine if you zip it.

Here’s my script in case it helps:
```
#!/bin/bash

# Navigate to the app directory
cd /home/site/wwwroot

# Run the Laravel queue worker
php artisan queue:work --sleep=3 --tries=3 --timeout=90
```

My queue is set as continuous instead of triggered, maybe that could be the issue? what if you change that and give it a try just to make sure it works with continuous

**Comment by oslotboom** [comment]
I created a webjob on 2025-02-12 and it was running successfully on a schedule. The job is ASP.Net 9 on a Linux host web app. I had only one environment variable defined, WEBSITES_ENABLE_APP_SERVICE.

On 2025-03-01, I discovered that the job was deleted. Looking at my run logs, it was deleted on 2025-02-26. I did not delete the webjob. It just disappeared.

I attempted to recreate the web job. This failed with the "Bad request" error.

I added the following environment variables, as recommended above

WEBSITE_SKIP_RUNNING_KUDUAGENT = false
WEBSITE_VNET_ROUTE_ALL = 1
WEBSITE_CONTENTOVERVNET = 1

Saving these changes hanged the main web site for a period of 5-10 minutes, but thankfully it started working normally.

After saving the changes, I was able to create the webjob and run it manually. (I did not test triggered.)

**Comment by malandles** [comment]
@veroca88 Thank you very much, was able to make it work even using triggered.

After putting all the environment variables, I also forced a restart and waited until it became available again.  Now the creation worked.
